server:
  port: 9003

spring:
  application:
    name: gradu-article

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gra_article?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "000000"
  redis:
    host: 47.97.162.247
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gradu.article.entity