server:
  port: 9004

spring:
  application:
    name: gradu-treehole
  data:
    mongodb:
      host: 47.97.162.247
      database: treehole
      port: 27017
      password: '000000'
      username: root
  redis:
    host: 47.97.162.247
    port: 6379
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true