server:
  port: 9004

spring:
  application:
    name: gradu-treehole
  data:
    mongodb:
      host: 47.97.162.247
      database: treehole

  redis:
    host: 47.97.162.247
    port: 6379
  jpa:
    show-sql: true

