server:
  port: 9007

spring:
  application:
    name: gradu-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.162.247:3306/gra_user?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "000000"
  redis:
    host: 47.97.162.247
    port: 6379
  rabbitmq:
    host: 47.97.162.247

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml

# token配置模板
#过期时间： 2小时（1000*60*60*2）
#私钥 base64加密
token:
  config:
    private_key: "JXU1MzVBJXU3ODFB"
    effective_time: 7200000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

oss:
  config:
    accessKeyId: LTAI4FteHG4Difnj6yK4ADPX
    accessKeySecret: Qx2EUW1SZ6UQMQh0z7eWAR5py0ryCy
    bucketName: gradu-boyan
    endPoint: oss-cn-shenzhen.aliyuncs.com
    domain: https://gradu-boyan.oss-cn-shenzhen.aliyuncs.com