server:
  port: 9007

spring:
  application:
    name: gradu-user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.162.247:3306/gra_user?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "000000"
  redis:
    host: 47.97.162.247
    port: 6379
  rabbitmq:
    host: 47.97.162.247

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# token配置模板
#过期时间： 2小时（1000*60*60*2）
#私钥 base64加密
token:
  config:
    effective_time: 7200000
    private_key: "JXU1MzVBJXU3ODFB"