server:
  port: 9002

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: gradu-qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.162.247:3306/gra_qa?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "000000"
  redis:
    host: 47.97.162.247
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gradu.qa.entity

token:
  config:
    private_key: "JXU1MzVBJXU3ODFB"

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true