server:
  port: 9008

spring:
  application:
    name: gradu-mq
  rabbitmq:
    host: 47.97.162.247

#阿里云短信配置
#账号
#私钥
#模板code
#签名
sms:
  aliyun:
    access_key_id: LTAI4FteHG4Difnj6yK4ADPX
    access_key_secret: Qx2EUW1SZ6UQMQh0z7eWAR5py0ryCy
    template_code: SMS_174990010
    sign_name: 博砚

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true