server:
  port: 9009

spring:
  application:
    name: gradu-friend
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.97.162.247:3306/gra_friend?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "000000"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

token:
  config:
    private_key: "JXU1MzVBJXU3ODFB"
